###TestInscriptionFull
POST http://localhost:8080/utilisateurs/inscription
Content-Type: application/x-www-form-urlencoded
Accept: */*

pseudo=sid&mdp=baptielpb&email=vincentlpb@camacho.fr&bio=salutcmoi&photoDeProfil=www.googleimage.fr/sidlpb


###ChangerPseudo expected=200
PATCH http://localhost:8080/utilisateurs/changementPseudo?email=vincentlpb@camacho.fr&nouveauPseudo=new_pseudo
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzY2Mzg5LCJpYXQiOjE3MTM3MzAzODksInNjb3BlIjoiIn0.FMqC1nO0HrAP2RSxh_SI_jWRs9_HmvR0SdJYr0yRTlIn3-V3IMoT04SdJuaautFdIss_aA2pZScocm0qR44pxfV9p7V7VspX6A7_dCddfuF217hW3E58fQOIp4tyor8A3efntGz94hJ4JCH5_fvavoIMFwA8jlyFVCn9hQqvFvkt6PU543gSCkDD1eE5HFg3b2P3B-uSKHN-KLInvMsQbVHjTgpd3aFKaDvYEZ8pp8o583RpaE51MzpIRryiwO9tqg6ch03RT19oi8LHFG8xi6iiy3m58ygrY102uj9pPdK7PrL2GMsWc5UCNs2ynsxqFlBgz9hZ9YQaI94sckVo5Q



###changementBio expected=200
PATCH http://localhost:8080/utilisateurs/changementBio?email=vincentlpb@camacho.fr&nouvelleBio=new_bio
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzY2Mzg5LCJpYXQiOjE3MTM3MzAzODksInNjb3BlIjoiIn0.FMqC1nO0HrAP2RSxh_SI_jWRs9_HmvR0SdJYr0yRTlIn3-V3IMoT04SdJuaautFdIss_aA2pZScocm0qR44pxfV9p7V7VspX6A7_dCddfuF217hW3E58fQOIp4tyor8A3efntGz94hJ4JCH5_fvavoIMFwA8jlyFVCn9hQqvFvkt6PU543gSCkDD1eE5HFg3b2P3B-uSKHN-KLInvMsQbVHjTgpd3aFKaDvYEZ8pp8o583RpaE51MzpIRryiwO9tqg6ch03RT19oi8LHFG8xi6iiy3m58ygrY102uj9pPdK7PrL2GMsWc5UCNs2ynsxqFlBgz9hZ9YQaI94sckVo5Q


###changementPhotoDeProfil expected=200
PATCH http://localhost:8080/utilisateurs/changementPhotoDeProfil?email=vincentlpb@camacho.fr&nouvellePhotoDeProfil=new_photo
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzY2Mzg5LCJpYXQiOjE3MTM3MzAzODksInNjb3BlIjoiIn0.FMqC1nO0HrAP2RSxh_SI_jWRs9_HmvR0SdJYr0yRTlIn3-V3IMoT04SdJuaautFdIss_aA2pZScocm0qR44pxfV9p7V7VspX6A7_dCddfuF217hW3E58fQOIp4tyor8A3efntGz94hJ4JCH5_fvavoIMFwA8jlyFVCn9hQqvFvkt6PU543gSCkDD1eE5HFg3b2P3B-uSKHN-KLInvMsQbVHjTgpd3aFKaDvYEZ8pp8o583RpaE51MzpIRryiwO9tqg6ch03RT19oi8LHFG8xi6iiy3m58ygrY102uj9pPdK7PrL2GMsWc5UCNs2ynsxqFlBgz9hZ9YQaI94sckVo5Q


###AJOUT CONTACT expected = 200
POST http://localhost:8080/utilisateurs/ajoutContact?pseudo1=new_pseudo&pseudo2=vince
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzY2Mzg5LCJpYXQiOjE3MTM3MzAzODksInNjb3BlIjoiIn0.FMqC1nO0HrAP2RSxh_SI_jWRs9_HmvR0SdJYr0yRTlIn3-V3IMoT04SdJuaautFdIss_aA2pZScocm0qR44pxfV9p7V7VspX6A7_dCddfuF217hW3E58fQOIp4tyor8A3efntGz94hJ4JCH5_fvavoIMFwA8jlyFVCn9hQqvFvkt6PU543gSCkDD1eE5HFg3b2P3B-uSKHN-KLInvMsQbVHjTgpd3aFKaDvYEZ8pp8o583RpaE51MzpIRryiwO9tqg6ch03RT19oi8LHFG8xi6iiy3m58ygrY102uj9pPdK7PrL2GMsWc5UCNs2ynsxqFlBgz9hZ9YQaI94sckVo5Q



###GET INFO COMPTE Expecte =200
GET http://localhost:8080/utilisateurs/new_pseudo
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzY2Mzg5LCJpYXQiOjE3MTM3MzAzODksInNjb3BlIjoiIn0.FMqC1nO0HrAP2RSxh_SI_jWRs9_HmvR0SdJYr0yRTlIn3-V3IMoT04SdJuaautFdIss_aA2pZScocm0qR44pxfV9p7V7VspX6A7_dCddfuF217hW3E58fQOIp4tyor8A3efntGz94hJ4JCH5_fvavoIMFwA8jlyFVCn9hQqvFvkt6PU543gSCkDD1eE5HFg3b2P3B-uSKHN-KLInvMsQbVHjTgpd3aFKaDvYEZ8pp8o583RpaE51MzpIRryiwO9tqg6ch03RT19oi8LHFG8xi6iiy3m58ygrY102uj9pPdK7PrL2GMsWc5UCNs2ynsxqFlBgz9hZ9YQaI94sckVo5Q




###DELETE COMPTE Expected = 200
DELETE http://localhost:8080/utilisateurs/suppressionCompte?email=vincentlpb@camacho.fr
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzY2Mzg5LCJpYXQiOjE3MTM3MzAzODksInNjb3BlIjoiIn0.FMqC1nO0HrAP2RSxh_SI_jWRs9_HmvR0SdJYr0yRTlIn3-V3IMoT04SdJuaautFdIss_aA2pZScocm0qR44pxfV9p7V7VspX6A7_dCddfuF217hW3E58fQOIp4tyor8A3efntGz94hJ4JCH5_fvavoIMFwA8jlyFVCn9hQqvFvkt6PU543gSCkDD1eE5HFg3b2P3B-uSKHN-KLInvMsQbVHjTgpd3aFKaDvYEZ8pp8o583RpaE51MzpIRryiwO9tqg6ch03RT19oi8LHFG8xi6iiy3m58ygrY102uj9pPdK7PrL2GMsWc5UCNs2ynsxqFlBgz9hZ9YQaI94sckVo5Q


